services:
  build-sandbox:
    build:
      context: ./deeppresenter/docker
      dockerfile: SandBox.Dockerfile
      network: host
      args:
        - HTTP_PROXY=http://127.0.0.1:7890
        - HTTPS_PROXY=http://127.0.0.1:7890
        - NO_PROXY=localhost,127.0.0.1,tsinghua.edu.cn,mirrors.tuna.tsinghua.edu.cn
    image: deeppresenter-sandbox:0.1.0
    profiles:
      - build-only

  deeppresenter-host:
    build:
      context: ./deeppresenter
      dockerfile: docker/Host.Dockerfile
      network: host
      args:
        - HTTP_PROXY=http://127.0.0.1:7890
        - HTTPS_PROXY=http://127.0.0.1:7890
        - NO_PROXY=localhost,127.0.0.1,tsinghua.edu.cn,mirrors.tuna.tsinghua.edu.cn
    image: deeppresenter-host:0.1.0
    runtime: runc
    container_name: deeppresenter-host
    ports:
      - "7861:7861"
    environment:
      DEEPPRESENTER_HOST_WORKSPACE_BASE: ${PWD}/workspace
      DEEPPRESENTER_WORKSPACE_BASE: /opt/workspace
      DEEPPRESENTER_LOG_LEVEL: 0 # 0: debug, 10: info, 20: warning
    volumes:
      - ./workspace:/opt/workspace
      - ./deeppresenter:/usr/src/pptagent/deeppresenter
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  deeppresenter_workspace: