import os
import json
import uuid
import tempfile
import fitz
import io
from PIL import Image, ImageFilter, ImageOps
from core import _log
from ppt_core import parse_resp_for_editor
from visuals import _normalize_focus_regions, _nms_regions

def _ensure_local_image_path(image_path_or_bytes, tmp_dir: str) -> str:
    if isinstance(image_path_or_bytes, str) and os.path.exists(image_path_or_bytes):
        return image_path_or_bytes
    if isinstance(image_path_or_bytes, (bytes, bytearray)):
        os.makedirs(tmp_dir, exist_ok=True)
        out_path = os.path.join(tmp_dir, f"vlm_{uuid.uuid4().hex}.png")
        with open(out_path, "wb") as f:
            f.write(bytes(image_path_or_bytes))
        return out_path
    return ""

def _prepare_vlm_image_local_path(image_path_or_bytes, tmp_dir: str) -> str:
    os.makedirs(tmp_dir, exist_ok=True)
    if isinstance(image_path_or_bytes, (bytes, bytearray)):
        out_path = os.path.join(tmp_dir, f"vlm_{uuid.uuid4().hex}.png")
        with open(out_path, "wb") as f:
            f.write(bytes(image_path_or_bytes))
        return out_path

    if not isinstance(image_path_or_bytes, str):
        return ""

    src_path = image_path_or_bytes
    if not os.path.exists(src_path):
        return ""

    ext = os.path.splitext(src_path)[1].lower()
    if ext in {".png", ".jpg", ".jpeg", ".webp", ".gif"}:
        return src_path

    if ext == ".pdf":
        try:
            doc = fitz.open(src_path)
            if doc.page_count <= 0:
                return ""
            page = doc.load_page(0)
            pix = page.get_pixmap(alpha=False)
            out_path = os.path.join(tmp_dir, f"vlm_{uuid.uuid4().hex}.png")
            pix.save(out_path)
            return out_path
        except Exception:
            return ""

    try:
        img = Image.open(src_path)
        out_path = os.path.join(tmp_dir, f"vlm_{uuid.uuid4().hex}.png")
        img.save(out_path, format="PNG")
        return out_path
    except Exception:
        return ""

def _call_vlm_beautify(image_path: str, latex_code: str) -> str:
    try:
        import dashscope
        from dotenv import load_dotenv
        
        env_path = os.path.join(os.path.dirname(__file__), '../config/env/.env')
        if os.path.exists(env_path):
            load_dotenv(env_path)
        else:
            # Fallback
            env_path = "/home/ym/DeepSlide/deepslide/config/env/.env"
            load_dotenv(env_path)
            pass
            
        api_key = os.getenv("DEFAULT_VLM_API_KEY")
        if not api_key:
            _log("VLM Error: DEFAULT_VLM_API_KEY not found.")
            return ""
            
        api_url = os.getenv("DEFAULT_VLM_API_URL")
        if api_url:
            dashscope.base_http_api_url = api_url
            
        model_type = os.getenv("DEFAULT_VLM_TYPE", "qwen-vl-max")
            
        local_file_url = f"file://{os.path.abspath(image_path)}"
        
        prompt = (
            "You are a Presentation Design Expert. "
            "Analyze the slide image and the corresponding LaTeX code. "
            "Your tasks are:\n"
            "1. Layout: Prevent any element overlap. If the content in `latex_code` does not fully appear in the image, it means there is too much content beyond the display range, and simplification or reduction is needed. \n"
            "2. Images: Check if images are too small or too large. Resize them to fit the slide comfortably (Recommend center-align images, and try not to use too much text in image pages).\n"
            "3. Content Density: Check if the slide has too much text (cluttered) or too little (empty). Balance the whitespace.\n"
            "Suggestions:\n"
            "- Do NOT use \\Large or \\textbf manually for slide titles inside the content area. Use \\frametitle{...} or \\framesubtitle{...} instead.\n"
            "- Do NOT add any footers, signatures, e.g., 'Generated by DeepSlide' text."
            "Return ONLY the modified \\begin{frame}...\\end{frame} block in ```latex``` code block."
        )
        
        messages = [
            {
                "role": "user",
                "content": [
                    {"image": local_file_url},
                    {"text": f"{prompt}\n\nCurrent LaTeX:\n```latex\n{latex_code}\n```"}
                ]
            }
        ]
        
        response = dashscope.MultiModalConversation.call(
            api_key=api_key,
            model=model_type,
            messages=messages,
            result_format="message"
        )
        
        if response.status_code == 200:
             if hasattr(response, 'output') and response.output.choices:
                content = response.output.choices[0].message.content
                if isinstance(content, list):
                    text = ""
                    for item in content:
                        if "text" in item: text += item["text"]
                    return parse_resp_for_editor(text)
                return parse_resp_for_editor(str(content))
        else:
             _log(f"VLM Failed: {response.code} - {response.message}")
             return ""
    except Exception as e:
        _log(f"VLM Error: {e}")
        return ""
    return ""

def _extract_first_json_object(text: str):
    if not text:
        return None
    start = text.find("{")
    if start < 0:
        return None
    depth = 0
    for i in range(start, len(text)):
        ch = text[i]
        if ch == "{":
            depth += 1
        elif ch == "}":
            depth -= 1
            if depth == 0:
                return text[start : i + 1]
    return None

def _call_vlm_focus_regions(slide_image_path_or_bytes, speech_text: str, max_regions: int = 5):
    try:
        import dashscope
        from dotenv import load_dotenv

        env_path = os.path.join(os.path.dirname(__file__), '../config/env/.env')
        if os.path.exists(env_path):
            load_dotenv(env_path)
        else:
            env_path = "/home/ym/DeepSlide/deepslide/config/env/.env"
            load_dotenv(env_path)

        api_key = os.getenv("DEFAULT_VLM_API_KEY")
        if not api_key:
            _log("VLM Error: DEFAULT_VLM_API_KEY not found.")
            return []

        api_url = os.getenv("DEFAULT_VLM_API_URL")
        if api_url:
            dashscope.base_http_api_url = api_url

        model_type = os.getenv("DEFAULT_VLM_TYPE", "qwen-vl-max")
        tmp_dir = os.path.join(tempfile.gettempdir(), "deepslide_vlm")
        local_path = _prepare_vlm_image_local_path(slide_image_path_or_bytes, tmp_dir)
        if not local_path:
            return []
        local_file_url = f"file://{os.path.abspath(local_path)}"

        speech_text = (speech_text or "").strip()
        if len(speech_text) > 1200:
            speech_text = speech_text[:1200]

        prompt = (
            "You are a vision-language model producing focus-zoom regions for a presentation image. "
            "Given an image and its narration, output an ordered list of rectangular regions to highlight. "
            "Prefer rectangles that correspond to salient blocks/figures/boxed areas already visible in the image (common in slides). "
            "If the most important target is unclear, choose a larger region that safely covers the plausible focus area rather than a tiny box. "
            "Return ONLY valid JSON with schema: {\"regions\": [{\"x\":0.0,\"y\":0.0,\"w\":0.2,\"h\":0.2,\"label\":\"...\"}, ...]}. "
            "Coordinates are normalized to the image (x,y,w,h in [0,1]). "
            f"Choose 3 to {max_regions} regions, avoid heavy overlap, and keep each region reasonably sized."
        )

        messages = [
            {
                "role": "user",
                "content": [
                    {"image": local_file_url},
                    {"text": f"{prompt}\n\nNarration:\n{speech_text}"}
                ]
            }
        ]

        response = dashscope.MultiModalConversation.call(
            api_key=api_key,
            model=model_type,
            messages=messages,
            result_format="message"
        )

        if response.status_code != 200:
            _log(f"VLM Failed: {response.code} - {response.message}")
            return []

        if not (hasattr(response, 'output') and response.output.choices):
            return []

        content = response.output.choices[0].message.content
        if isinstance(content, list):
            text = ""
            for item in content:
                if "text" in item:
                    text += item["text"]
        else:
            text = str(content)

        json_text = _extract_first_json_object(text)
        if not json_text:
            return []
        data = json.loads(json_text)
        regions = data.get("regions") if isinstance(data, dict) else None

        return _normalize_focus_regions(regions, max_regions=max_regions)

    except Exception as e:
        _log(f"VLM Focus Regions Error: {e}")
        return []

def _detect_focus_regions_heuristic(image_path_or_bytes, max_regions: int = 5):
    """Simplified heuristic region detection using standard Pillow filters."""
    try:
        if isinstance(image_path_or_bytes, str) and os.path.exists(image_path_or_bytes):
            im = Image.open(image_path_or_bytes)
        else:
            im = Image.open(io.BytesIO(bytes(image_path_or_bytes)))
        im = ImageOps.exif_transpose(im).convert("L")
        w, h = im.size
        if w < 16 or h < 16: return []

        # Resize for speed
        scale = min(1.0, 512.0 / max(w, h))
        sw, sh = int(w * scale), int(h * scale)
        im_small = im.resize((sw, sh), Image.BILINEAR)

        # Edge detection + Blur to find dense areas
        edges = im_small.filter(ImageFilter.FIND_EDGES)
        blurred = edges.filter(ImageFilter.GaussianBlur(radius=3))
        
        # Grid based selection (simpler than sliding window)
        grid_rows, grid_cols = 4, 4
        cell_w, cell_h = sw / grid_cols, sh / grid_rows
        
        cells = []
        import numpy as np
        arr = np.array(blurred) # (sh, sw)
        
        for r in range(grid_rows):
            for c in range(grid_cols):
                y1, y2 = int(r * cell_h), int((r+1) * cell_h)
                x1, x2 = int(c * cell_w), int((c+1) * cell_w)
                score = float(arr[y1:y2, x1:x2].mean())
                if score > 5: # Threshold
                    cells.append((score, c, r))
        
        cells.sort(key=lambda x: x[0], reverse=True)
        top_cells = cells[:max_regions*2]
        
        regions = []
        for score, c, r in top_cells:
            # Create a region slightly larger than the cell
            # Normalized coordinates
            cx = (c + 0.5) * (1/grid_cols)
            cy = (r + 0.5) * (1/grid_rows)
            # Box size: 1.5x cell size
            rw = 1.5 / grid_cols
            rh = 1.5 / grid_rows
            
            regions.append({
                "x": max(0, cx - rw/2),
                "y": max(0, cy - rh/2),
                "w": min(1.0, rw),
                "h": min(1.0, rh),
                "label": ""
            })

        # NMS
        regions = _nms_regions(regions, iou_thr=0.1, max_regions=max_regions)
        return regions
    except Exception:
        return []

def _get_focus_regions(slide_image_path_or_bytes, speech_text: str, max_regions: int = 5, prefer_vlm: bool = True):
    regions = []
    if prefer_vlm:
        regions = _call_vlm_focus_regions(slide_image_path_or_bytes, speech_text, max_regions=max_regions)
    if not regions:
        regions = _detect_focus_regions_heuristic(slide_image_path_or_bytes, max_regions=max_regions)
    return _normalize_focus_regions(regions, max_regions=max_regions)
